version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: .
      args:
        SERVICE_NAME: api-gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  booking-service:
    build:
      context: .
      args:
        SERVICE_NAME: booking-service
    restart: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  event-service:
    build:
      context: .
      args:
        SERVICE_NAME: event-service
    restart: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  notification-service:
    build:
      context: .
      args:
        SERVICE_NAME: notification-service
    restart: always
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: .
      args:
        SERVICE_NAME: user-service
    restart: always
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data: