version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: event-booking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - event-booking-network

  mongodb:
    image: mongo
    container_name: event-booking-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-booking-network

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  event-booking-network:
    driver: bridge